<?php

namespace App\Http\Requests;

use App\Models\EntryRecord;
use Illuminate\Foundation\Http\FormRequest;

class AddEntryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'patient_id' => ['required', 'integer', 'exists:patients,id'],
            'entry_at' => ['required', 'date_format:Y-m-d']
        ];
    }

    public function validated($key = null, $default = null)
    {
        parent::validated($key, $default); // TODO: Change the autogenerated stub

        return $this;
    }

    public function save() : EntryRecord {
        return EntryRecord::create([
            'patient_id' => $this->request->get('patient_id'),
            'entry_at' => $this->request->get('entry_at')
        ]);
    }
}
