<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use App\Models\Patient;
use App\Models\EntryRecord;

class AddPatientRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => ['required', 'string', 'max:50'],
            'phone' => ['required', 'numeric', 'digits:13', 'unique:patients,phone'],
            'address' => ['required', 'string', 'max:255'],
            'status' => ['required', 'in:recovered,positive,death'],
            'entry_at' => ['required', 'date_format:Y-m-d']
        ];
    }

    public function validated($key = null, $default = null)
    {
        parent::validated($key, $default); // TODO: Change the autogenerated stub

        return $this;
    }

    public function save() : Patient {
        $patient = Patient::create([
            'name' => $this->get('name'),
            'phone' => $this->get('phone'),
            'address' => $this->get('address'),
            'status' => $this->get('status')
        ]);

        EntryRecord::create([
            'patient_id' => $patient->id,
            'entry_at' => $this->get('entry_at')
        ]);

        return $patient;
    }
}
